### ISSUE TITLE
Suggestion: Allow usage with dimensions created by mods

### ISSUE THREAD

**Issue by ghost** [InspireNXE/TimeWarp#1]
I haven't actually had a chance to install this and try it out yet, but I [note](https://github.com/InspireNXE/TimeWarp/blob/master/src/main/java/org/inspirenxe/timewarp/Storage.java#L64) that TimeWarp only affects worlds with the Overworld dimension type. For compatibility with modded dimensions, might it be a better idea to invert this - i.e. so that it only affects worlds whose dimension types are _not_ the Nether or the End?

Alternatively, Forge has a method `World#getHasNoSky()`, which returns `false` for the Overworld and `true` for the Nether and the End; modded dimensions can then override it. I don't know whether there's a similar method in the Sponge API, but if there is, it might be another way of accomplishing this.

**Comment by Grinch** [comment]
I garnered some feedback about this and instead I think I will add somewhere in the configuration file the ability to specify which dimensions you would like to allow.

**Comment by ghost** [comment]
That works too. :)

**Comment by Grinch** [comment]
Addressed in e73a31109bc1cebd51482c81b5f8a6ebbc11f463
