### ISSUE TITLE
Console Error - Plugin isn't working

### ISSUE THREAD

**Issue by Yorkforce** [InspireNXE/TimeWarp#3]
Currently running into issues trying to get this working on Horizons III modpack

This is the error we are seeing in the forge startup log:
https://pastebin.com/agfFWCAs

And this is the current config:
https://pastebin.com/5Kv6pZCP

**Comment by Grinch** [comment]
I'll have a new release this evening that might resolve this. I'll update this issue when I release it.

**Comment by Grinch** [comment]
Well. Now that I'm awake enough and read the log again your biggest issue is you put TimeWarp in the plugins folder and not the mods folder. Plugin Mixins cannot work unless the plugin is in the mods folder.

Please report back if that resolves your issue.

**Comment by Yorkforce** [comment]
Hmm, we set the sponge config to use the plugins folder
`        plugins-dir="${CANONICAL_GAME_DIR}/plugins"`
Will TimeWarp work with that setting if we place it inside the actual modpacks mods folder?
You mention the Plugin Mixins, is this a separate plugin we need to add or is it something that sponge already has?

I do recall Nucleus also used a separate Mixins plugin that would go into the mods folder by itself, it was removed for 1.12 I think but putting sponge plugins into the mods folder would be a huge headache for us as updating the server when a new modpack version is released would mean we would have to start manually separating plugins and configs from the modpack files.

**Comment by Grinch** [comment]
Unfortunately not. It is noted on the main Ore page for TimeWarp as well as in Sponge's documentation: https://docs.spongepowered.org/stable/en/server/management/plugins.html (see bottom of the Installation - SpongeForge block).

This is solely a limitation with SpongeForge and not of TimeWarp. I believe if you wanted to make it a bit more sane you might be able to do `/mods/plugins` instead of `/mods`.

**Comment by Yorkforce** [comment]
Ok moved everything over to the /mods/plugins directory, same error as before.

I'm still a bit unsure about Mixins plugin, is that built into spongeforge or do i need to download and add that to the mods folder seperately? (or the /mods/plugins folder?)

**Comment by Grinch** [comment]
No. My plugin uses mixins which are included with SpongeVanilla and SpongeForge.

Try just /mods and see if that resolves it.

**Comment by Yorkforce** [comment]
Think thats got it, for the first time the timewarp config actually added the world data itself, hasn't done that before

**Comment by Grinch** [comment]
Awesome. I'll close this issue. Feel free to open another if you run in to problems.

I'd make a ticket on SpongeForge for the `/plugins` and `/mods/plugins` issue and maybe they can figure something out.

**Comment by Yorkforce** [comment]
Will do thanks Grinch!
Just to clarify if anyone else runs into the same issue
The plugins folder must be in the /mods directory (/mods/plugins) and the TimeWarp plugin must be in the /mods folder itself.
You can use the /mods/plugins/config path for the config, it works fine.
A separate /plugins directory doesn't work even if the TimeWarp plugin is in the /mods folder.
